spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: development
sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem